name: RemielCore
main: me.taylan.mooncore.MoonCore
version: 1.0.0
api-version: 1.18
author: Taylan
depend: [ CrazyAdvancementsAPI, CoreProtect, ProtocolLib, Vault, RealisticSeasons]
load: STARTUP

commands:
  ustalık:
  discord:
  statekle:
  profil:
  seviye:
  bookver:
  nitelik:
  claimset:
  back:
  oynanansure:
  npcolustur:
  lore:
  isim:
  lootolustur:
  dirhem:
  warp:
  adminitem:
  iteminfo:
  xpadd:
  map:
  skillget:
  bc:
  questget:
  furnacereset:
  dura: